# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gerlein Advocacia
page: Excelência em assuntos de Família e Sucessão
email: contacto@gerlein.pt
description: >- # this means to ignore newlines until "baseurl:"
  Somos um escritório de advocacia especializado em Direito de Família, das Sucessões e Direito Internacional Privado. Prezamos pela técnica, excelência e ética.
keywords: direito, família, familia, sucessão, sucessões, sucessao, sucessoes, mãe, mae, pai, pais, padrasto, madrasta, irmão, irmao, irmãos, irmaos, neto, netos, parentesco, filho, filhos, menor, menores, guarda, judicial, alimentos, responsabilidade, responsabilidades, parental, parentais, convenção, Haia, Hage, convenções, convencoes,  antinupcial, antenupciais,  herança, heranca
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gerlein.pt/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
facebook_username:

# Build settings
markdown: kramdown
theme: minima
theme: agency-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
